import React, { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, BookOpen, Shield, ShieldAlert, UserCheck, HelpCircle, FileText, CheckCircle } from "lucide-react";
import "./TermsOfUse.css";

const SECTIONS = [
  {
    id: "intermediary",
    title: "1. Introduction & Intermediary Disclosure",
    icon: BookOpen,
    content: `This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2021 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”).

The Platform is owned by ShopEase Internet Private Limited, an Indian enterprise. Your use of the Platform and services are governed by these terms and conditions including the applicable policies which are incorporated herein by way of reference.`
  },
  {
    id: "membership",
    title: "2. Membership Eligibility",
    icon: UserCheck,
    content: `Transaction on the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Platform. 

If you are a minor i.e. under the age of 18 years, you may use the Platform or access content on the Platform only under the supervision and prior consent/permission of a parent or legal guardian. ShopEase reserves the right to terminate your membership and / or refuse to provide you with access to the Platform if it is discovered that You are under the age of 18 years and transacting on the Platform without appropriate supervision.`
  },
  {
    id: "account",
    title: "3. Account & Registration Obligations",
    icon: Shield,
    content: `If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. 

You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform.

Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Platform. It is your responsibility to ensure that Your mobile phone number and your email address is up to date on the Platform at all times, verified through one-time password (OTP) verification.`
  },
  {
    id: "transactions",
    title: "4. Platform for Transaction & Communication",
    icon: HelpCircle,
    content: `The Platform enables Buyers and Sellers to transact online. ShopEase is not and cannot be a party to or control in any manner any transaction between the Platform's Users. All commercial and contractual terms are offered by and agreed to between Buyers and Sellers alone. 

The commercial/contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties related to products and services and after sales services related to products. ShopEase does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers.`
  },
  {
    id: "charges",
    title: "5. Charges & Platform Fees",
    icon: FileText,
    content: `ShopEase may charge a nominal platform fee for browsing and buying on the Platform to sustain efficient operations and continuous platform improvement. ShopEase reserves the right to change its Fee Policy from time to time. 

Convenience fees, transport fees (GT Charges) for delivery facilitated by third-party transporters, and other logistics fees will be clearly displayed to customers on the order page before placing the order. Ownership of products transfers directly from the Seller to the Buyer once products are handed over to the Transporter.`
  },
  {
    id: "conduct",
    title: "6. User Code of Conduct",
    icon: ShieldAlert,
    content: `You agree, undertake and confirm that Your use of Platform shall be strictly governed by the following binding principles. You shall not host, display, upload, modify, publish, transmit, update or share any information which belongs to another person and to which You do not have any right to; is defamatory, obscene, pornographic, invasive of another's privacy, hateful, or racially/ethnically objectionable; infringes any patent, trademark, copyright or other proprietary rights; contains software viruses; or threatens the unity, integrity, defence, security or sovereignty of India or public order.

You shall not use any automatic device like page-scrape, robot, or spider to monitor or copy any portion of the Platform, nor attempt to gain unauthorized access to any systems or networks connected to the Platform by hacking or password mining.`
  },
  {
    id: "infant",
    title: "7. Infant Food Category Regulations",
    icon: CheckCircle,
    content: `In accordance with the Infant Milk Substitutes, Feeding Bottles and Infant Foods (Regulation of Production, Supply and Distribution) Act, 1992 (IMS Act) and health guidelines, we state that 'MOTHER'S MILK IS BEST FOR YOUR BABY'. 

Infant milk substitutes and infant foods should be used only on the professional advice of a medical practitioner or health worker as to the need for and the proper method of its use.`
  },
  {
    id: "drugs",
    title: "8. Prescription & Non-Prescription Drugs",
    icon: CheckCircle,
    content: `The pharmaceutical information on this website is for general information purposes only and is not intended as a substitute for professional medical advice, diagnosis, or treatment. ShopEase makes no representation and assumes no responsibility for the accuracy of information contained on or available through this website. 

For prescription-only drugs required by law, orders are confirmed by Sellers only after a valid medical prescription has been uploaded, validated, and approved by independent licensed retail chemist pharmacies.`
  },
  {
    id: "healthcare",
    title: "9. Diagnostic & Teleconsultation Services",
    icon: CheckCircle,
    content: `ShopEase facilitates connections to independent licensed Third Party Service Providers and Registered Medical Professionals. ShopEase is not responsible for Diagnostic Services or Teleconsultation advice and acts strictly as a bridge. 

Any teleconsultation advice, issues, or prescriptions generated by practitioners are the sole responsibility of the Registered Medical Professional. Reliance on any teleconsultation or diagnostic reports is at Your own risk. The Teleconsultation Services are not for use in medical emergencies.`
  },
  {
    id: "gst",
    title: "10. GST Invoicing & Business Purchases",
    icon: CheckCircle,
    content: `Select products offered by sellers may be eligible for business purchases on the Platform, enabling You to claim GST input tax credit. An invoice containing the GSTIN and Entity Name provided by You ("Tax Invoice") shall be issued by the Seller. 

ShopEase and the Sellers shall not entertain any request for post-purchase revision of GST invoices, and You are solely responsible for compliance and providing accurate credentials.`
  },
  {
    id: "tobacco",
    title: "11. Tobacco Products Restrictions",
    icon: CheckCircle,
    content: `You agree and undertake that You will not use the Platform to transact for the purchase of Tobacco products on the Platform if You are below the age of eighteen years (twenty-one if ordering in the state of Karnataka, or other age limits established under local statutory regulations). 

Age verification criteria are strictly enforced for tobacco-related merchant categories.`
  },
  {
    id: "warranties",
    title: "12. Disclaimer of Warranties & Indemnity",
    icon: ShieldAlert,
    content: `This Platform, all the materials, products, and services, included on or otherwise made available to You through this site are provided on an "as is" and "as available" basis without any representation or warranties, express or implied, except otherwise specified in writing.

You release and indemnify ShopEase and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the Users of the Platform and specifically waive any claims that you may have in this behalf under any applicable law.`
  }
];

const TermsOfUse = () => {
  const [activeSection, setActiveSection] = useState(SECTIONS[0].id);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const handleSectionClick = (id) => {
    setActiveSection(id);
    const element = document.getElementById(id);
    if (element) {
      const offset = 90; // Header sticky offset
      const bodyRect = document.body.getBoundingClientRect().top;
      const elementRect = element.getBoundingClientRect().top;
      const elementPosition = elementRect - bodyRect;
      const offsetPosition = elementPosition - offset;

      window.scrollTo({
        top: offsetPosition,
        behavior: "smooth"
      });
    }
  };

  return (
    <div className="terms-page-container">
      {/* Header Breadcrumbs */}
      <div className="terms-header-nav">
        <Link to="/" className="terms-back-link">
          <ArrowLeft size={16} />
          <span>Back to Home</span>
        </Link>
        <div className="terms-badge-tag">ShopEase Legal</div>
      </div>

      <div className="terms-hero-section">
        <h1>Terms of Use</h1>
        <p className="terms-last-updated">Last Updated: June 1, 2026</p>
        <p className="terms-subtitle">
          Please read these terms of use carefully before accessing, browsing, or otherwise using our marketplace platform.
        </p>
      </div>

      <div className="terms-layout-grid">
        {/* Left Sticky Sidebar */}
        <aside className="terms-sidebar-nav">
          <div className="sidebar-scroll-box">
            <h3>Table of Contents</h3>
            <ul className="sidebar-link-list">
              {SECTIONS.map((sec) => {
                const IconComponent = sec.icon;
                return (
                  <li key={sec.id}>
                    <button
                      onClick={() => handleSectionClick(sec.id)}
                      className={`sidebar-nav-btn ${activeSection === sec.id ? "active" : ""}`}
                    >
                      <IconComponent size={16} className="sidebar-icon" />
                      <span>{sec.title.split(". ")[1]}</span>
                    </button>
                  </li>
                );
              })}
            </ul>
          </div>
        </aside>

        {/* Right Scrollable Content Pane */}
        <main className="terms-content-pane">
          <div className="terms-disclaimer-card">
            <ShieldAlert size={20} className="disclaimer-icon" />
            <div className="disclaimer-text">
              <strong>Electronic Record Disclosure:</strong> In case of any discrepancy or difference, 
              the English version of these Terms of Use takes precedence. This platform operates strictly as 
              an intermediary facilitator connecting Buyers and Sellers under standard marketplace principles.
            </div>
          </div>

          <div className="terms-sections-list">
            {SECTIONS.map((sec) => {
              const IconComponent = sec.icon;
              return (
                <section key={sec.id} id={sec.id} className="terms-content-section">
                  <div className="section-title-wrap">
                    <div className="section-title-icon-box">
                      <IconComponent size={20} />
                    </div>
                    <h2>{sec.title}</h2>
                  </div>
                  <div className="section-body-text">
                    {sec.content.split("\n\n").map((para, idx) => (
                      <p key={idx}>{para}</p>
                    ))}
                  </div>
                  <div className="section-end-divider" />
                </section>
              );
            })}
          </div>
        </main>
      </div>
    </div>
  );
};

export default TermsOfUse;
